name: "Modpack Bug Report"
description: "File a bug report for the modpack."
title: "[Bug - {{modpack_version}}] "
labels: [bug]
assignees: []
body:
- type: markdown
  attributes:
    value: |
      **Do NOT remove `'{{modpack_version}}'` from the title.**  
      This will be automatically replaced with the information you provide below.
- type: input
  id: modpack_version
  attributes:
    label: "Modpack version"
    placeholder: "e.g. 1.0"
  validations:
    required: true
- type: textarea
  id: steps_to_reproduce
  attributes:
    label: "Steps to reproduce"
    description: "Provide the exact steps needed to reproduce the bug."
    placeholder: "1. ...\n2. ...\n3. ..."
  validations:
    required: true
- type: textarea
  id: expected_behavior
  attributes:
    label: "Expected behavior"
    description: "What did you expect to happen?"
  validations:
    required: true
- type: textarea
  id: actual_behavior
  attributes:
    label: "Actual behavior"
    description: "What actually happened instead?"
  validations:
    required: true
- type: textarea
  id: additional_info
  attributes:
    label: "Additional information"