name: "Mod Addition Request"
description: "Request a new mod to be added to the modpack."
title: "[Mod Addition] {{mod_name}}"
labels: [enhancement]
assignees: []
body:
- type: markdown
  attributes:
    value: |
      **Do NOT remove `'{{mod_name}}'` from the title.**  
      This will be automatically replaced with the information you provide below.
- type: input
  id: mod_name
  attributes:
    label: "Mod name"
    placeholder: "e.g. Example Mod"
  validations:
    required: true
- type: input
  id: mod_url
  attributes:
    label: "Mod URL"
    value: "https://curseforge.com/minecraft/mc-mods/"
    placeholder: "e.g. https://curseforge.com/minecraft/mc-mods/mod"
  validations:
    required: true
- type: textarea
  id: alternatives_considered
  attributes:
    label: "Alternatives considered"
    description: "Describe any alternatives you've considered."
- type: textarea
  id: additional_info
  attributes:
    label: "Additional information"