name = "KenkuKraft: Infected"
author = "furglitch"
version = "2.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68d77bae3190c393c9ab012368457b2e9c117ba133eb1da806e6c85b4748c5e4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
datapack-folder = "config/paxi/datapacks"
