name = "KenkuKraft: Infected"
author = "furglitch"
version = "2.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce5429ffbca882ed051722a03fa85c63eaa9045b376aed96787d8df82236f948"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
datapack-folder = "config/paxi/datapacks"
