name = "KenkuKraft: Infected"
author = "furglitch"
version = "2.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5715d2f70811010202d69de5b7dcb30cc0435515dd1759dd26bf67cc699811cd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
datapack-folder = "config/paxi/datapacks"
