

// Guns
ServerEvents.tags('item', event => {
    event.add('kenkukraft:filters_pointblank_guns', '@pointblank')

    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:.*suppressor.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:.*grip.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:.*muzzlebreak.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:.*scope.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:.*stock.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:.*sight.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:.*laser.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:.*muzzlebreak$/)

    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:ammo.*$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:grenade.*$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:.*rocket$/)

    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_fang$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_katana.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_tomahawk.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:hl_crowbar$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:hl_rebar$/)

    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:1913telescopic$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:acog$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:aimpoint.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cantedrail$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_cerberus.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_chimera.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_clearvue_mk8$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_cqo_kanone_mini_mk72$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_e255_percipient.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_e305_prospecta$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_gaki.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_hpo_kanone_max_mk77.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_hypercritical_red_skin$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_kanetsugu$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_mk2x_grandstand$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_os1_gimleteye$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_so21_saika$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_type_2067$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cp2077_xc_10_.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:cs2skins$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:delta$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:doom_launcher$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:doom_precisionbolt$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:fn40$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:gp25$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:hamr$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:hi_red.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:holographic.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:1p29/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:m16a3kit$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:m203launcher$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:m4sopmodii_bartender$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:mid_zf39$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:moa.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:operatorreflex$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:p30l_compensator$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:ppco$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:rspec$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:scarl_iss$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:spear.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:specter$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:srs$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:star15mod3receiver$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:ulg99cannon$/)

    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:10_4_47mmr$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:11_58mmr$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:13_2mmtuf$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:14_5_114mm$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:30_06_springfield$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:303_british$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:351_winchester_self_loading$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:577_450_martini$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:6_5_50mmsr_arisaka$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:6_5_52mm_carcano$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:7_62_25mm_tokarev$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:7_62_54mmr$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:7_65_53mm_mauser$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:7_92_57mm_mauser$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:8_35mm_ribeyrolles$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:8_50mmr_.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:9_23mm_steyr$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:doom_50cal.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:doom_argentblastcharge$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:doom_plasmacell$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:mid_panzerfaust60_warhead$/)

    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:m1helmet$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:stahlhelm.*$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:flakvest$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:us_.*$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:binocular$/)

    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:doom_argent_.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:doom_steelflechette$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:guninternals$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:gunmetal_.*/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:motor$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:processor$/)

    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:workstation$/)
    event.remove('kenkukraft:filters_pointblank_guns', /^pointblank:printer$/)
})

// Ammo
ServerEvents.tags('item', event => {
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:ammo.*/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:grenade.*/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:.*rocket$/)
    event.remove('kenkukraft:filters_pointblank_ammo', 'pointblank:ammocreative')

    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:10_4_47mmr$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:11_58mmr$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:13_2mmtuf$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:14_5_114mm$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:30_06_springfield$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:303_british$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:351_winchester_self_loading$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:577_450_martini$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:6_5_50mmsr_arisaka$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:6_5_52mm_carcano$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:7_62_25mm_tokarev$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:7_62_54mmr$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:7_65_53mm_mauser$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:7_92_57mm_mauser$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:8_35mm_ribeyrolles$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:8_50mmr_.*/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:9_23mm_steyr$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:doom_50cal.*/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:doom_argentblastcharge$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:doom_plasmacell$/)
    event.add('kenkukraft:filters_pointblank_ammo', /^pointblank:mid_panzerfaust60_warhead$/)
})

// Attachments
ServerEvents.tags('item', event => {
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:.*suppressor.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:.*grip.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:.*muzzlebreak.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:.*scope.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:.*stock.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:.*sight.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:.*laser.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:.*muzzlebreak$/)

    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:1913telescopic$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:acog$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:aimpoint.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cantedrail$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cp2077_cerberus.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cp2077_chimera.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cp2077_clearvue_mk8$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cp2077_cqo_kanone_mini_mk72$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cp2077_e255_percipient.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cp2077_e305_prospecta$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cp2077_gaki.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cp2077_hpo_kanone_max_mk77.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cp2077_hypercritical_red_skin$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cp2077_kanetsugu$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cp2077_mk2x_grandstand$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cp2077_os1_gimleteye$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cp2077_so21_saika$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cp2077_type_2067$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cp2077_xc_10_.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:cs2skins$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:delta$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:doom_launcher$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:doom_precisionbolt$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:fn40$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:gp25$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:hamr$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:hi_red.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:holographic.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:1p29/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:m16a3kit$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:m203launcher$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:m4sopmodii_bartender$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:m870modshotgunr$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:mid_zf39$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:moa.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:operatorreflex$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:p30l_compensator$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:ppco$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:rspec$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:scarl_iss$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:spear.*/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:specter$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:srs$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:star15mod3receiver$/)
    event.add('kenkukraft:filters_pointblank_attachments', /^pointblank:ulg99cannon$/)
})